# Answer 1

In [1]:
import numpy as np

array = np.arange(2, 51, 3)

print(array)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Answer 2

In [9]:
import numpy as np

list1 = []
list2 = []

for i in range(5):
    l1 = int(input("\nEnter elements for List1 :"))
    list1.append(l1)
    
print("List one =",list1)

for i in range(5):
    l2 = int(input("\nEnter elements for List2 :"))
    list2.append(l2)
    
print("List two =",list2)



#coversion of Lists to numpy array

array1 = np.array(list1)
array2 = np.array(list2)
print("\nConversion of List one to array :",array1)
print("\nConversion of List two to array :",array2)


#Concatenation of arrays

concat = np.concatenate((array1,array2))
    
print("\nConcatenation of array1 and array2 are :",concat)

#Sorting of arrays

print("\nSorting of Array :",np.sort(concat))



Enter elements for List1 :1

Enter elements for List1 :6

Enter elements for List1 :4

Enter elements for List1 :3

Enter elements for List1 :8
List one = [1, 6, 4, 3, 8]

Enter elements for List2 :2

Enter elements for List2 :7

Enter elements for List2 :5

Enter elements for List2 :9

Enter elements for List2 :0
List two = [2, 7, 5, 9, 0]

Conversion of List one to array : [1 6 4 3 8]

Conversion of List two to array : [2 7 5 9 0]

Concatenation of array1 and array2 are : [1 6 4 3 8 2 7 5 9 0]

Sorting of Array : [0 1 2 3 4 5 6 7 8 9]


# Answer 3

In [8]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("\nDimensions of nd array =",arr.ndim)
print("\nSize of an Array =",arr.size)


Dimensions of nd array = 2

Size of an Array = 9


# Answer 4

In [17]:
import numpy as np


arr = np.arange(int(input()))
print("\nShape of 1D array :",arr.shape)

arr_row = arr[np.newaxis, :]
print("\nShape of 2D Array in row major :",arr_row.shape)

arr_col = arr[:, np.newaxis]
print("\nShape of 2D Array in column major :",arr_col.shape)

10

Shape of 1D array : (10,)

Shape of 2D Array in row major : (1, 10)

Shape of 2D Array in column major : (10, 1)


# Answer 5

In [19]:
import numpy as np

arr1 = np.square([2,4,6])
arr2 = np.square([8,9,10])

print("\nHorizontally Stacked :", np.hstack((arr1,arr2)))
print("\nVertically Stacked :", np.vstack((arr1,arr2)))


Horizontally Stacked : [  4  16  36  64  81 100]

Vertically Stacked : [[  4  16  36]
 [ 64  81 100]]


# Answer 6

In [24]:
import numpy as np

arr = np.array([1,5,8,2,3,5,9,7,6])

unique, counts = np.unique(arr,return_counts=True)
arr = np.asarray((unique, counts)).T

print(arr)

[[1 1]
 [2 1]
 [3 1]
 [5 2]
 [6 1]
 [7 1]
 [8 1]
 [9 1]]
